In [1]:
import torch

In [2]:
tensor1 = torch.randint(0,139,(5,3,2,))
print(tensor1.size())
print(tensor1.ndim)     
print(tensor1.shape)    # Samesies as size()
print(tensor1[0][0][0].item())   # Only utilisable by scalars, or individual elements inside the tensor
print(tensor1.dtype)

torch.Size([5, 3, 2])
3
torch.Size([5, 3, 2])
23
torch.int64


In [5]:
tensor2 = torch.zeros(3,4,2)
tensor3 = torch.zeros_like(tensor1)
tensor2.dtype, tensor3.shape, tensor3.dtype

(torch.float32, torch.Size([5, 3, 2]), torch.int64)

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
    dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
    device=None, # defaults to None, which uses the default tensor type
    requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device    # Defines which chip its using, cpu or gpu
# gpu only works with cuda or 

device(type='cpu')

In [12]:
# Basic Operations
tensor1 = torch.tensor([3,-5,7])
add = tensor1 + 10  # OR torch.add(tensor1,10)
sub = tensor1 - 10  # OR torch.sub(tensor1,10)
mul = tensor1 * 4   # OR torch.mul(tensor1, 4)
print(tensor1)
print(add)
print(sub)
print(mul)
print(torch.matmul(tensor1, tensor1))

tensor([ 3, -5,  7])
tensor([13,  5, 17])
tensor([ -7, -15,  -3])
tensor([ 12, -20,  28])
tensor(83)


In [15]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # Changed tensor_B to transpose, thus matrix multiplication is possible

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
tensor1 = torch.arange(0,758,12,).reshape(4,4,4).transpose(0,2)
# Fun, first have a range of numbers, start, end, steps, then reshape it to a new shape, then transpose the 0th and 2nd dimensional matrix
# Keep in mind that the size should match the number of elements
tensor1

RuntimeError: shape '[4, 4, 5]' is invalid for input of size 64