In [1]:
import torch

In [2]:
tensor1 = torch.randint(0,139,(5,3,2,))
print(tensor1.size())
print(tensor1.ndim)     
print(tensor1.shape)    # Samesies as size()
print(tensor1[0][0][0].item())   # Only utilisable by scalars, or individual elements inside the tensor
print(tensor1.dtype)

torch.Size([5, 3, 2])
3
torch.Size([5, 3, 2])
23
torch.int64


In [5]:
tensor2 = torch.zeros(3,4,2)
tensor3 = torch.zeros_like(tensor1)
tensor2.dtype, tensor3.shape, tensor3.dtype

(torch.float32, torch.Size([5, 3, 2]), torch.int64)

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
    dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
    device=None, # defaults to None, which uses the default tensor type
    requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device    # Defines which chip its using, cpu or gpu
# gpu only works with cuda or 

device(type='cpu')

In [12]:
# Basic Operations
tensor1 = torch.tensor([3,-5,7])
add = tensor1 + 10  # OR torch.add(tensor1,10)
sub = tensor1 - 10  # OR torch.sub(tensor1,10)
mul = tensor1 * 4   # OR torch.mul(tensor1, 4)
print(tensor1)
print(add)
print(sub)
print(mul)
print(torch.matmul(tensor1, tensor1))

tensor([ 3, -5,  7])
tensor([13,  5, 17])
tensor([ -7, -15,  -3])
tensor([ 12, -20,  28])
tensor(83)


In [15]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # Changed tensor_B to transpose, thus matrix multiplication is possible

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [28]:
tensor1 = torch.arange(0,758,12,).reshape(4,4,4).transpose(0,2)
# Fun, first have a range of numbers, start, end, steps, then reshape it to a new shape, then transpose the 0th and 2nd dimensional matrix
# Keep in mind that the size should match the number of elements

tensor1

tensor([[[  0, 192, 384, 576],
         [ 48, 240, 432, 624],
         [ 96, 288, 480, 672],
         [144, 336, 528, 720]],

        [[ 12, 204, 396, 588],
         [ 60, 252, 444, 636],
         [108, 300, 492, 684],
         [156, 348, 540, 732]],

        [[ 24, 216, 408, 600],
         [ 72, 264, 456, 648],
         [120, 312, 504, 696],
         [168, 360, 552, 744]],

        [[ 36, 228, 420, 612],
         [ 84, 276, 468, 660],
         [132, 324, 516, 708],
         [180, 372, 564, 756]]])

In [32]:
torch.manual_seed(149)  # Manual seeds basically help in order of random generation of values
tens_rand = torch.rand(4,2)
torch.manual_seed(149)
tens_rand2 = torch.rand(4,2)
tens_rand == tens_rand2

tensor([[True, True],
        [True, True],
        [True, True],
        [True, True]])

In [41]:
# Window Funcs
min = tens_rand.min()
max = tens_rand.max()
max_int = (10*tens_rand).type(torch.int32).max()
pos_max = tens_rand.argmax()
min, max, max_int, pos_max

(tensor(0.1904), tensor(0.8041), tensor(8, dtype=torch.int32), tensor(2))

In [ ]:
x = torch.arange(1,8)
# Resizing: Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape  # Same as x_reshaped, but only a view of x

# Changing z changes x
z[:, 0] = 5
z, x    # z = [[5,2,3,4,5,6,7]]

(tensor([[5, 2, 3, 4, 5, 6, 7]]), tensor([5, 2, 3, 4, 5, 6, 7]))

In [48]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # dim 0 does on first dimension, and so on
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]])

In [54]:
print(f"Previous tensor: {x_stacked}")
print(f"Previous shape: {x_stacked.shape}")

# Add extra dimension to x_stacked
x_squeezed = x_stacked.unsqueeze(dim=0)
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7]])
Previous shape: torch.Size([7, 4])

New tensor: tensor([[[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7]]])
New shape: torch.Size([1, 7, 4])


In [56]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [59]:
# Set device type, cuda, cpu, mps
if torch.cuda.is_available():
    device = "cuda" # Use NVIDIA GPU (if available)
elif torch.backends.mps.is_available():
    device = "mps" # Use Apple Silicon GPU (if available)
else:
    device = "cpu" # Default to CPU if no GPU is available
device

'mps'

In [60]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='mps:0')